# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://anubansal17.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Anu Bansal

# Short description of your site
description: Fueling my passion

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Blogs: "blogs"
  About Me: "aboutme"
  Projects:
    - Improving Production Sized Code Coverage: "https://github.com/anubansal17/Code-Coverage-Using-Plugins"
    - Secured Blockchain based Exams System: "https://github.com/anubansal17/Secured-Blockchain-Based-Examination-Management-System"
    #- Local E-selling App: "https://github.com/anubansal17/Local-e-Selling-Android-App/tree/master"
    - Eye Disease Prediction Model: "https://github.com/anubansal17/Leukocoric-Eye-Prediction-Model"
  Coding Profiles:
    - Codechef: "https://www.codechef.com/users/anubansal17"
    - Leetcode: "https://leetcode.com/anubansal17/"
    - InterviewBit: "https://www.interviewbit.com/profile/anubansal17"
    - Hackerrank: "https://www.hackerrank.com/anubansal17?hr_r=1"
  Resume / CV: "https://drive.google.com/open?id=1-p6WNMW73fRA5GWIwGxazVujJ9fehrfx"
  
# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
#avatar: "/img/avatar-icon.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: AB
  email: "anubansal9999@gmail.com"
  #facebook: divyam.madaan.1  # eg. daattali
  github: anubansal17   
  twitter: anu_bansal17  
  #reddit: yourname    # eg. daattali
  #google-plus: +yourname   # eg. +DeanAttali or 109424658772469020925
  linkedin: anubansal17  # eg. daattali
  #xing: yourname      # eg. daattali
  #stackoverflow: yourlink  # eg. "3943160/daattali"
  #snapchat: yourname  # eg. daattali
  instagram: anu__bansal # eg. daattali
  #youtube: yourlink   # eg. user/daattali or channel/daattali
  #spotify: yourname   # eg. daattali
  #telephone: yourphone   # eg. +14159998888

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: true
  email: true
  twitter: true
  google-plus: false
  github: true
  reddit: false
  linkedin: true
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: true
  youtube: false
  spotify: false
  telephone: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: UA-88654744-1

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: false

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

gems:
  - jekyll-paginate

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

theme: jekyll-theme-midnight
